from datetime import datetime
from typing import List, Optional

class LineContent:
    date: datetime
    line_count: int
    line: str

    def __init__(self, date: datetime, line_count: int, line: str) -> None: ...

class History:
    def __init__(self, data: str) -> None: ...
    @staticmethod
    def read_from_file(filename: str) -> "History": ...
    @staticmethod
    def from_lines(lines: List[str]) -> "History": ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def search_by_date(self, date: datetime) -> Optional[str]: ...
    def search_by_keyword(self, keyword: str) -> List[LineContent]: ...
    def search_by_random(self) -> Optional[str]: ...
