# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import datetime
import typing

class Chat:
    def time(self) -> datetime.time:
        ...

    def speaker(self) -> typing.Optional[builtins.str]:
        ...

    def message_lines(self) -> builtins.list[builtins.str]:
        ...


class Day:
    def date(self) -> datetime.date:
        ...

    def chats(self) -> builtins.list[Chat]:
        ...

    def search_by_keyword(self, keyword:builtins.str) -> builtins.list[tuple[datetime.date, Chat]]:
        ...


class History:
    def __new__(cls,days:typing.Mapping[datetime.date, Day]): ...
    @staticmethod
    def read_from_file(path:builtins.str) -> History:
        ...

    @staticmethod
    def from_text(text:builtins.str) -> History:
        ...

    def search_by_date(self, date:datetime.date) -> typing.Optional[Day]:
        ...

    def search_by_keyword(self, keyword:builtins.str) -> builtins.list[tuple[datetime.date, Chat]]:
        ...

    def search_by_random(self) -> Day:
        ...

    def days(self) -> builtins.dict[datetime.date, Day]:
        ...

    def len(self) -> builtins.int:
        ...

    def is_empty(self) -> builtins.bool:
        ...


